apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginxhello-hr
  namespace: default
  annotations:
    fluxcd.io/ignore: "false"
spec:
  chart:
    git: ssh://git@github.com/victoravr/gitops-nginxhello.git
    path: helm/chart
    ref: master
  rollback:
    enable: true
    retry: true
  values: 
    image: 
      tag: 1.19.1